package com.coddicted.school.sample;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.coddicted.school.sample.model.Sample;
import com.coddicted.school.sample.repo.SampleRepository;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
@Api(description = "The first REST API - created for Demo only")
public class MainController {

  private static Logger logger = LoggerFactory.getLogger(MainController.class);

  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private SampleRepository userRepository;

  @GetMapping(path = "/add") // Map ONLY GET Requests
  @ApiOperation(code = 200, value = "Add a new sample to the DB")
  public @ResponseBody String addNewSample(@RequestParam String name, @RequestParam String email) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    logger.info("logging the addNewSample method inside MainController");

    Sample n = new Sample();
    n.setName(name);
    n.setEmail(email);
    userRepository.save(n);
    return "Saved";
  }

  @GetMapping(path = "/all")
  @ApiOperation(code = 200, value = "Get all the saved samples")
  public @ResponseBody Iterable<Sample> getAllSamples() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }
}
